[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "ledger-service"
internalPort = 8082

[[services]]
name = "ledger-grpc"
internalPort = 9090
protocol = "grpc"
